### ISSUE TITLE
Use Azure Active Directory as an external user store

### ISSUE THREAD

**Issue by bingosummer** [cloudfoundry-attic/login-server#54]
Azure Active Directory supports SAML to enable SSO. And UAA also supports connecting to external user stores through LDAP and SAML. For SAML, my understanding is configuring a saml_login_server.
Does that mean I can integrate Azure AD with UAA and login-server just by changing configuration?
Thanks.

**Comment by fhanik** [comment]
Closing - duplicate of https://github.com/cloudfoundry/uaa/issues/213
